feature/feedback button
McMaster-Engineering-Society/MES-Website-App-Router pull request #470
Opened 2024-11-09 21:11 UTC by AnnabellebwWoo

# Description & Technical Solution

Created a feedback button and removed part of alert banner that asked for feedback. Currently vertically aligned with booking tabs and right justified. Grey and white when unused, red and white when hovering.

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] Already rebased against main branch.

# Screenshots

https://github.com/user-attachments/assets/f264676c-6832-4212-8db0-0bad27e2e343

# Issue number

2024-11-10 21:55 UTC, HagOrMan requested changes
In addition to what we talked about, here's some coding related feedback!

2024-11-10 21:55 UTC, HagOrMan commented on package.json
> +    "@types/node": "22.8.6",
Do you know why this was added?

2024-11-10 21:55 UTC, HagOrMan commented on src/app/page.tsx
> +            src='https://drive.google.com/file/d/1fK54lTaZTufW1RfrQ-iqMxd49S5jDpkl/preview'
Did you change this? It looks like you rebased off staging instead of staging-hatch?

2024-11-10 21:55 UTC, HagOrMan commented on src/slices/hatch/booking-page/components/FeedbackButton.tsx
> +import React from 'react';
When it comes to something as simple as styling a button, there's no need to make a new component! You can just put it in the page itself.

2024-11-10 21:55 UTC, HagOrMan commented on src/slices/hatch/booking-page/components/FeedbackButton.tsx
> +  <Button
If you use a ButtonLink instead of a button, it'll handle linking to a new tab better for you! It'll also make it obvious for users that it's a link because when hovering over it, your mouse looks like the new tab mouse

2024-11-17 04:25 UTC, closed without merging

2024-11-17 04:25 UTC, BaoGeist commented
Closed as a newer one was created, fixing some past issues.

https://github.com/McMaster-Engineering-Society/MES-Website-App-Router/pull/506

2024-11-17 04:31 UTC, BaoGeist commented on package.json
> +    "@types/node": "22.8.6",
Think there was an out of date issue. Annabelle mentioned it was flaky but it was a suggested fix. Will monitor for in later PRs