Feature/new clubs and teams page
McMaster-Engineering-Society/MES-Website-App-Router pull request #486
Opened 2024-11-10 23:50 UTC by ritual-17

# Description & Technical Solution
This PR updates the clubs-and-teams page styling and migrates it to the slice architecture. It also prepares for displaying uploaded clubs.

Each club card currently has placeholder data for description and email.

When narrowing a search, the cards tend to render ok, but when broadening the search (i.e. deleting your query), the card profile pictures will take a split second to load sometimes. I tried to mitigate this with the react query stuff but its still there. I didn't know a way to make this smoother when the cards are unmounting. My original solution was having the `clubs` array stay constant after initial load and then setting any card who doesnt match the query to `classname='hidden'`, meaning no cards unmount but rather go invisible. This made it feel much nicer and snappier, but sacrified using fuse.js for better fuzzy searching and ranking, so i ended up switching to the implementation in this PR. You can checkout the old implementation: `be27d4e1a872c2ec3ac7ca18b3db7653cbc461ba`.

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] Already rebased against main branch.

# Screenshots
![image](https://github.com/user-attachments/assets/df3c143c-d842-4a88-8b6b-59b57a6e5458)
![image](https://github.com/user-attachments/assets/326dbfa6-c43b-459d-b9c4-b6ddbdb64d68)

Provide screenshots or videos of the changes made if any.

# Issue number

Closes # number

2024-11-14 03:31 UTC, ritual-17 commented on src/slices/clubs-and-teams/services/clubsTeamsServices.ts
> +  const baseURL = process.env.NEXT_PUBLIC_URL || 'http://localhost:3000';
just want to confirm this looks right

2024-11-19 01:50 UTC, BaoGeist requested changes
Looks good except for one code location thing.

I also changed the scrollbars in the clubs cards to be `scroll-x-auto`.

2024-11-19 01:50 UTC, BaoGeist commented on src/slices/clubs-and-teams/services/clubsTeamsServices.ts
> +  const baseURL = process.env.NEXT_PUBLIC_URL || 'http://localhost:3000';
Looks good! Though we would prefer if you moved any database access layers to the `clubsTeamsDb` file, just so if we ever are to change the database call, we know we'd change it from the database layer. I know it's a little bit of an edge case since it's not actually a "database" call in a traditional sense, so sorry about that!

2024-11-22 05:39 UTC, BaoGeist approved these changes
lgtm

2024-11-22 05:40 UTC, merged