Feature/admin form view modal
McMaster-Engineering-Society/MES-Website-App-Router pull request #487
Opened 2024-11-11 02:04 UTC by wonyuan

# Description & Technical Solution

Describe problems, if any, clearly and concisely.
Summarize the impact to the system.
Please also include relevant motivation and context.
Please include a summary of the technical solution and how it solves the problem.

- Added ui for admin comment and functionality to save/edit comments 
- User can reject/approve form, comments and form decision returned in json object upon form decision
- Still needs to be completely connected to the backend; further updates for where the form goes after being rejected and approved to also be added once the other rejected/approved pages are completed.

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] Already rebased against main branch.

# Screenshots

Provide screenshots or videos of the changes made if any.
<img width="1003" alt="Screenshot 2024-11-10 at 8 51 45 PM" src="https://github.com/user-attachments/assets/b71ede26-2bad-4e1e-a36f-56f89a39a7ce">
<img width="711" alt="Screenshot 2024-11-10 at 8 51 58 PM" src="https://github.com/user-attachments/assets/3510c369-5d3f-4138-bf2f-1da4ac0ce264">

#113 Issue number

Closes #113  number

2024-11-19 01:34 UTC, HagOrMan requested changes
Made some comments on improvements and also left questions.
Also, we need to rebase this off of `staging-clubs` and modify it to use the slices architecture like the rest of the code.
UI looks great though, I'm loving the frontend!

2024-11-19 01:34 UTC, HagOrMan commented on src/components/clubs-portal/EventApprovalPages/ApprovedPage.tsx
> +export default ApprovedPage;
Can I ask why this was done this way? Is it meant to be extended later and this is an mvp version of it?

2024-11-19 01:34 UTC, HagOrMan commented on src/components/clubs-portal/EventApprovalPages/PendingPage.tsx
> +      <div className='flex flex-col w-[25rem] px-[2.5rem] mt-5'>
Can we make any of the filters here reusable?

2024-11-19 01:34 UTC, HagOrMan commented on src/components/clubs-portal/EventsApproval.tsx
> +  const [selected, setSelected] = useState('pending');
it would be good to define the different states in this statement for useState.

2024-11-19 01:34 UTC, HagOrMan commented on src/components/clubs-portal/EventsApproval.tsx
> +        <ErrorPage />
A dictionary mapping states to pages could work well here too!

2024-11-19 01:34 UTC, HagOrMan commented on src/components/clubs-portal/EventApprovalPages/ApprovedPage.tsx
> +    <div>
Also, is there a need to have a surrounding div tag? Is it just there for when more is added?

2024-11-19 01:34 UTC, HagOrMan commented on src/components/clubs-portal/FormEvent.tsx
> +    //console.log('rejected:', formData);
can we get rid of console logs if they aren't being used anymore?

2024-11-19 01:34 UTC, HagOrMan commented on src/components/clubs-portal/FormEvent.tsx
> +          </div>
In the next PR which makes this page more modular, I guess we'll refactor this general div into a reusable component?

2024-11-19 01:34 UTC, HagOrMan commented on src/components/clubs-portal/FormEvent.tsx
> +}
I would say to remove unused comments, but if you think this is genuinely useful to understand something specific about the page, maybe put it at the top and comment on what this would be used for?

2024-11-25 21:11 UTC, wonyuan commented on src/components/clubs-portal/EventApprovalPages/ApprovedPage.tsx
> +export default ApprovedPage;
ooh not sure i think the general pending page they was made by fayez

2024-12-30 03:52 UTC, closed without merging